#!/usr/bin/env python3
"""Type inventory and license evidence for the engine built with GraalVM CE
(Prompts 34/35; engine/scripts/build-wasm.sh). Two commands:

  sbom      GraalVM CE has no class-level SBOM (--enable-sbom is an Oracle
            GraalVM feature). This builds its replacement from the list of
            reachable types that engine/scripts/sbom/ReachableTypesFeature.java writes after
            the builder's analysis (the set Oracle's class-level SBOM lists), in the
            CycloneDX shape the engine scripts read (components with
            class/interface properties). Types whose source file exists in the
            labsjdk-ce src.zip or in the oracle/graal checkout at the pinned
            commit get an "open:" component (JDK, or the GraalVM suite they come
            from); all other types (Forge, OpenMana, Maven libraries) stay
            unassociated, as in Oracle's SBOM, and are attributed to their JARs
            by scripts/notices/engine-inventory.py.

  evidence  For every type the toolchain (JDK or GraalVM) put into the module:
            source file at the pinned state and its license header. Class names
            alone prove nothing: a type counts as open only when its source
            file exists and carries a GPLv2 + Classpath Exception, UPL-1.0 or
            Apache-2.0 header (or is shaded Guava/Jimfs, Apache-2.0). Works for
            Oracle's SBOM too (for comparison). Also checks the launcher's
            license headers and that the closed binary-load.js is absent.

  python3 -I inventory.py sbom <reachable-types.txt> <graal-checkout> <java-home with lib/src.zip> <jdk-version> > x.sbom.json
  python3 -I inventory.py evidence <build-dir> <graal-checkout> <jdk-home> > license-evidence.json
"""
import json
import re
import sys
import zipfile
from collections import Counter, defaultdict
from pathlib import Path

HEADER_LINES = 40
KIND_RE = r'(?:class|interface|enum|record|@interface)'
GENERATED_PROXY = 'generated by java.lang.reflect.Proxy (java.base, GPL-2.0-only WITH Classpath-exception-2.0)'
OPEN = ('GPL-2.0-only WITH Classpath-exception-2.0', 'UPL-1.0', 'Apache-2.0', GENERATED_PROXY)
SHADED = 'org.graalvm.shadowed.com.google.'
# SubstrateVM ships Espresso's class-file parser renamed from com.oracle.truffle.espresso.
ESPRESSO = ('com.oracle.svm.espresso.', 'com.oracle.truffle.espresso.')
# Hidden classes the JVM generates while building (lambdas: Host$$Lambda/0x...).
# Oracle's class-level SBOM leaves them out as well; they are code of their host
# class and are counted separately (metadata.hiddenTypes).
HIDDEN = re.compile(r'/0x[0-9a-f]+$')
GRAAL_PACKAGES = ('jdk.graal.', 'org.graalvm.', 'com.oracle.svm.', 'com.oracle.graal.', 'com.oracle.truffle.')
PROXY = re.compile(r'(^|\.)\$Proxy\d+$')


def classify(text):
    head = '\n'.join(text.splitlines()[:HEADER_LINES])
    if 'Classpath' in head and 'GNU General Public License' in head:
        return OPEN[0]
    if 'Universal Permissive License' in head or 'UPL' in head:
        return OPEN[1]
    if 'Apache License' in head:
        return OPEN[2]
    if 'GNU General Public License' in head:
        return 'GPL-2.0-only (no Classpath Exception)'
    return 'no header'


class Sources:
    """package -> {file name -> (location, origin, text getter)} for one source tree."""

    def __init__(self):
        self.by_package = defaultdict(dict)

    def find(self, type_name):
        top = type_name.split('$', 1)[0]
        package, _, simple = top.rpartition('.')
        files = self.by_package.get(package)
        if not files:
            return None
        if simple + '.java' in files:
            return files[simple + '.java']
        pattern = re.compile(r'\b' + KIND_RE + r'\s+' + re.escape(simple) + r'\b')
        for entry in files.values():
            if pattern.search(entry[2]()):
                return entry
        return None


def jdk_sources(jdk_home):
    src = Sources()
    archive = zipfile.ZipFile(Path(jdk_home) / 'lib' / 'src.zip')
    for name in archive.namelist():
        if not name.endswith('.java') or name.count('/') < 2:
            continue
        module, rest = name.split('/', 1)
        package = rest.rsplit('/', 1)[0].replace('/', '.')
        src.by_package[package][rest.rsplit('/', 1)[1]] = (
            f'src.zip:{name}', 'jdk', (lambda n=name: archive.read(n).decode('utf-8', 'replace')))
    return src


def graal_sources(checkout):
    src = Sources()
    root = Path(checkout)
    for path in root.glob('*/src/*/src/**/*.java'):
        parts = path.relative_to(root).parts
        package = '.'.join(parts[4:-1])
        src.by_package[package].setdefault(
            path.name, (str(path.relative_to(root)), parts[0], (lambda p=path: p.read_text('utf-8', 'replace'))))
    return src


def lookup(type_name, jdk, graal):
    """(location, origin, license) of a toolchain type, or None for Forge/OpenMana/libraries."""
    if type_name.startswith(SHADED):
        return ('shaded Guava/Jimfs (Maven artifacts pinned by mx)', 'shaded-google', 'Apache-2.0')
    if PROXY.search(type_name):
        return ('dynamic proxy class generated while building', 'jdk', GENERATED_PROXY)
    if type_name.startswith(ESPRESSO[0]):
        type_name = ESPRESSO[1] + type_name[len(ESPRESSO[0]):]
    # The GraalVM home's src.zip also carries GraalVM's own modules (compiler,
    # SDK): their packages belong to the oracle/graal suite. Everything else is
    # looked up in the JDK first (oracle/graal holds copies of some JDK classes).
    if type_name.startswith(GRAAL_PACKAGES):
        hit = graal.find(type_name) or jdk.find(type_name)
    else:
        hit = jdk.find(type_name) or graal.find(type_name)
    if hit is None:
        return None
    return (hit[0], hit[1], classify(hit[2]()))


def git_head(checkout):
    head = Path(checkout) / '.git' / 'HEAD'
    return head.read_text().strip() if head.exists() else None


def sbom(types_file, checkout, jdk_home, jdk_version):
    interfaces = set()
    reachable = []
    hidden = []
    for line in Path(types_file).read_text('utf-8').splitlines():
        kind, _, name = line.partition(' ')
        if kind not in ('class', 'interface') or not name:
            raise ValueError(f'unexpected line in {types_file}: {line!r}')
        if HIDDEN.search(name):
            hidden.append(name)
            continue
        reachable.append(name)
        if kind == 'interface':
            interfaces.add(name)
    jdk = jdk_sources(jdk_home)
    graal = graal_sources(checkout)
    commit = git_head(checkout)
    groups = defaultdict(list)
    for name in sorted(set(reachable)):
        found = lookup(name, jdk, graal)
        groups[None if found is None else found[1]].append(name)

    def props(names):
        return [{'name': 'interface' if n in interfaces else 'class', 'value': n} for n in names]

    # Same nesting as Oracle's class-level SBOM (component -> module -> types):
    # scripts/notices/engine-inventory.py owns the types of components that
    # have a group and child components.
    def component(ref, group, cname, version, names):
        return {'type': 'library', 'bom-ref': ref, 'group': group, 'name': cname, 'version': version,
                'components': [{'type': 'library', 'name': cname, 'properties': props(names)}]}

    components = []
    for origin, names in sorted(groups.items(), key=lambda kv: (kv[0] is None, kv[0] or '')):
        if origin is None:
            name = 'class-level metadata that could not be associated with a component'
            components.append({'type': 'data', 'bom-ref': name, 'name': name,
                               'components': [{'type': 'library', 'name': 'unassociated', 'properties': props(names)}]})
        elif origin == 'jdk':
            components.append(component(f'open:labsjdk-ce:{jdk_version}', 'open', 'labsjdk-ce', jdk_version, names))
        else:
            components.append(component(f'open:graalvm-ce-{origin}:{commit}', 'open', f'graalvm-ce-{origin}', commit, names))
    json.dump({'bomFormat': 'CycloneDX', 'specVersion': '1.5', 'version': 1,
               'metadata': {'tools': [{'name': 'engine/scripts/sbom/inventory.py sbom', 'source': 'ReachableTypesFeature (GraalVM CE analysis universe)'}],
                            'graalCommit': commit, 'types': Path(types_file).name,
                            'hiddenTypes': len(hidden),
                            'hiddenByHostPackage': dict(Counter(h.split('$$')[0].rsplit('.', 1)[0] for h in hidden).most_common())},
               'components': components}, sys.stdout, indent=1)
    sys.stdout.write('\n')


def sbom_types(component):
    found = {p['value'] for p in component.get('properties', [])
             if p['name'] in ('class', 'interface', 'annotation')}
    for child in component.get('components', []):
        found |= sbom_types(child)
    return found


def evidence(build, checkout, jdk_home):
    build = Path(build)
    data = json.loads((build / 'report/engine-sbom.class-level.json').read_text())
    components = {}
    owner = {}
    for c in data['components']:
        ref = c.get('bom-ref') or c.get('name')
        types = sbom_types(c)
        components[ref] = {'group': c.get('group'), 'name': c.get('name'), 'version': c.get('version'), 'types': len(types)}
        for t in types:
            owner[t] = ref
    jdk = jdk_sources(jdk_home)
    graal = graal_sources(checkout)
    rows = {}
    licenses = Counter()
    by_component = defaultdict(Counter)
    for t in sorted(owner):
        found = lookup(t, jdk, graal)
        if found is None:
            continue
        rows[t] = {'component': owner[t], 'source': found[0], 'license': found[2]}
        licenses[found[2]] += 1
        by_component[owner[t]][found[2]] += 1
    launcher = (build / 'dist/openmana-engine.js').read_text('utf-8', 'replace')
    json.dump({
        'format': 'openmana-open-license-evidence/1',
        'graalCommit': git_head(checkout),
        'sbomTypes': len(owner),
        'components': components,
        'toolchainTypes': len(rows),
        'toolchainLicenses': dict(licenses),
        'toolchainByComponent': {k: dict(v) for k, v in sorted(by_component.items())},
        'notOpen': {t: r for t, r in rows.items() if r['license'] not in OPEN},
        'launcher': {
            'classpathExceptionHeaders': launcher.count('"Classpath" exception'),
            'oracleProprietaryHeaders': launcher.count('ORACLE PROPRIETARY'),
            'binaryLoadJs': 'binary-load' in launcher,
        },
        'types': rows,
    }, sys.stdout, indent=1)
    sys.stdout.write('\n')


if __name__ == '__main__':
    if len(sys.argv) == 6 and sys.argv[1] == 'sbom':
        sbom(*sys.argv[2:])
    elif len(sys.argv) == 5 and sys.argv[1] == 'evidence':
        evidence(*sys.argv[2:])
    else:
        sys.exit(__doc__)
