#!/usr/bin/env bash
# Assembles the disposable build tree engine/build/work:
#
#   work/forge   the engine's Forge modules (core, game, ai, gui sources) taken
#                from the pinned submodule commit with `git archive`, then the
#                patch queue engine/patches/*.patch applied in order
#   work/bridge  a copy of engine/bridge plus generated build facts
#   work/pom.xml Maven reactor: the four Forge modules + bridge
#
# The submodule itself is never modified, and every build starts from a fresh
# tree, so no stale class or patch state can leak into an engine build.
source "$(dirname "$0")/lib.sh"

om_require_node
om_require_cmd git "git fehlt."
om_check_forge_checkout

pinned="$(om_forge_pinned_sha)"
om_log "Forge-Pin: Card-Forge/forge@$pinned"

rm -rf "$OM_WORK_DIR"
mkdir -p "$OM_WORK_DIR/forge"

git -C "$OM_FORGE_SUBMODULE" archive --format=tar "$pinned" \
    pom.xml checkstyle.xml forge-core forge-game forge-ai forge-gui/pom.xml forge-gui/src \
    | tar -x -C "$OM_WORK_DIR/forge"

# A throwaway repository makes `git apply` resolve paths against the Forge
# root and keeps one commit per patch for inspection (git -C … log).
(
    cd "$OM_WORK_DIR/forge"
    git init -q
    git config user.name "OpenMana engine build"
    git config user.email "engine-build@openmana.invalid"
    git add -A
    git commit -q -m "Card-Forge/forge@$pinned (engine subset)"
)

shopt -s nullglob
patches=("$OM_ENGINE_DIR"/patches/*.patch)
shopt -u nullglob
[ "${#patches[@]}" -gt 0 ] || om_die "Keine Patches in engine/patches gefunden."
for patch in "${patches[@]}"; do
    name="$(basename "$patch")"
    git -C "$OM_WORK_DIR/forge" apply --check "$patch" 2>/dev/null \
        || { git -C "$OM_WORK_DIR/forge" apply --check -v "$patch" || true; om_die "Patch $name passt nicht auf Forge $pinned. Patch an den neuen Forge-Stand anpassen (engine/patches/README.md)."; }
    git -C "$OM_WORK_DIR/forge" apply --index "$patch"
    git -C "$OM_WORK_DIR/forge" commit -q -m "$name"
    om_log "Patch angewendet: $name"
done
patches_sha256="$(cat "${patches[@]}" | sha256sum | awk '{print $1}')"

mkdir -p "$OM_WORK_DIR/bridge"
(cd "$OM_ENGINE_DIR/bridge" && tar -c --exclude=./target . ) | tar -x -C "$OM_WORK_DIR/bridge"

openmana_commit="$(git -C "$OM_REPO_DIR" rev-parse HEAD)"
openmana_dirty="false"
if [ -n "$(git -C "$OM_REPO_DIR" status --porcelain -- engine ':!engine/forge')" ]; then
    openmana_dirty="true"
fi
forge_version="$(sed -n 's:.*<versionCode>\(.*\)</versionCode>.*:\1:p' "$OM_WORK_DIR/forge/pom.xml" | head -1)"
mkdir -p "$OM_WORK_DIR/bridge/src/main/resources/openmana"
cat > "$OM_WORK_DIR/bridge/src/main/resources/openmana/engine-build.properties" <<EOF
forge.commit=$pinned
forge.versionCode=$forge_version
patches.count=${#patches[@]}
patches.sha256=$patches_sha256
openmana.commit=$openmana_commit
openmana.engineSourcesModified=$openmana_dirty
EOF

cat > "$OM_WORK_DIR/pom.xml" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by engine/scripts/prepare-forge.sh. Reactor for the engine build:
     the patched Forge modules the engine needs plus the OpenMana bridge. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.openmana</groupId>
    <artifactId>openmana-engine-reactor</artifactId>
    <version>0</version>
    <packaging>pom</packaging>
    <modules>
        <module>forge/forge-core</module>
        <module>forge/forge-game</module>
        <module>forge/forge-ai</module>
        <module>forge/forge-gui</module>
        <module>bridge</module>
    </modules>
</project>
EOF

mkdir -p "$OM_REPORT_DIR"
node -e '
const fs = require("fs");
const [file, commit, versionCode, count, sha, names] = process.argv.slice(1);
fs.writeFileSync(file, JSON.stringify({ forgeCommit: commit, forgeVersionCode: versionCode, patchCount: +count, patchesSha256: sha, patches: names.split(" ") }, null, 2) + "\n");
' "$OM_REPORT_DIR/forge-source.json" "$pinned" "$forge_version" "${#patches[@]}" "$patches_sha256" "$(for p in "${patches[@]}"; do basename "$p"; done | tr '\n' ' ' | sed 's/ $//')"
om_log "Arbeitsbaum bereit: $OM_WORK_DIR (${#patches[@]} Patches, sha256 ${patches_sha256:0:12}…)"
