/*
 * Generates the TypeScript side of the local data schema from its only
 * source, src/storage/schema/local-data.schema.json (the same way
 * engine/protocol/scripts/generate.mjs does it for the engine protocol):
 *
 *   src/storage/generated/records.ts      types (json-schema-to-typescript)
 *   src/storage/generated/constants.ts    SCHEMA_VERSION, BACKUP_FORMAT_VERSION and enums as runtime lists
 *   src/storage/generated/validators.js   precompiled validators (Ajv standalone code:
 *                                         no eval at run time, no Ajv in the bundle)
 *   src/storage/generated/validators.d.ts their types
 *
 *   npm run generate                        write the files
 *   node scripts/generate-storage.ts --check fail if they are not what the schema gives
 *
 * The generated files are committed: a schema change shows up in review as a
 * diff of types and validators. `npm run check` and `npm run build` run the
 * check first, so a forgotten regeneration fails instead of shipping stale
 * validators.
 */
import fs from "node:fs"
import path from "node:path"
import { Ajv2020 } from "ajv/dist/2020.js"
import standalone from "ajv/dist/standalone/index.js"
import { compile, type JSONSchema } from "json-schema-to-typescript"

const root = path.resolve(import.meta.dirname, "..")
const schemaFile = path.join(root, "src/storage/schema/local-data.schema.json")
const outDir = path.join(root, "src/storage/generated")

const HEADER = [
  "/*",
  " * GENERATED by scripts/generate-storage.ts from",
  " * src/storage/schema/local-data.schema.json. Do not edit: change the schema",
  " * and run `npm run generate`.",
  " */",
].join("\n")

/** The public validators: export name -> definition in the schema. */
const VALIDATORS: Readonly<Record<string, string>> = {
  validateDeckRecord: "DeckRecord",
  validateSettingRecord: "SettingRecord",
  validateMatchRecord: "MatchRecord",
  validateMatchLogEntry: "MatchLogEntry",
  validateCardRecord: "CardRecord",
  validateCacheEntryRecord: "CacheEntryRecord",
  validateMetaRecord: "MetaRecord",
  validateBackupHeader: "BackupHeader",
  validateBackupRecordLine: "BackupRecordLine",
  validateBackupEnd: "BackupEnd",
}

/** Enums exported as runtime lists: constant name -> definition. */
const ENUM_LISTS: Readonly<Record<string, string>> = {
  DECK_FORMATS: "DeckFormat",
  DECK_SOURCE_KINDS: "DeckSourceKind",
  MATCH_STATUSES: "MatchStatus",
  GAME_RESULTS: "GameResult",
  CACHE_STATUSES: "CacheStatus",
  IMPORT_MODES: "ImportMode",
  BACKUP_STORES: "BackupStore",
}

interface SchemaDocument {
  readonly $schema: string
  readonly $id: string
  readonly title: string
  readonly $defs: Record<string, Record<string, unknown>>
}

class GenerateError extends Error {}

function fail(message: string): never {
  throw new GenerateError(message)
}

function readSchema(): SchemaDocument {
  return JSON.parse(fs.readFileSync(schemaFile, "utf8")) as SchemaDocument
}

/**
 * A discriminated union (MetaRecord) carries `type`/`required`/`discriminator`
 * next to its oneOf for the validators. Every branch repeats the
 * discriminator, so for the types the plain union of the branches is the
 * same type and reads better than the intersection the tool would render.
 */
function schemaForTypes(schema: SchemaDocument): SchemaDocument {
  const copy = structuredClone(schema)
  for (const def of Object.values(copy.$defs)) {
    if (Array.isArray(def["oneOf"])) {
      const discriminator = (def["discriminator"] as { propertyName?: string } | undefined)?.propertyName
      for (const branch of def["oneOf"] as { $ref?: string }[]) {
        const target = branch.$ref ? copy.$defs[branch.$ref.replace("#/$defs/", "")] : undefined
        if (!target?.["title"]) fail(`union ${String(def["title"])}: every branch must be a $ref to a titled definition`)
        if (discriminator && !(target["required"] as string[] | undefined)?.includes(discriminator)) {
          fail(`union ${String(def["title"])}: branch ${String(target["title"])} must require '${discriminator}' itself`)
        }
      }
      delete def["type"]
      delete def["required"]
      delete def["properties"]
      delete def["discriminator"]
    }
  }
  return copy
}

async function generateTypes(schema: SchemaDocument): Promise<string> {
  // json-schema-to-typescript declares $defs only below an object root, so the
  // definitions are compiled under a synthetic empty object that is removed again.
  const copy = schemaForTypes(schema)
  const syntheticRoot = {
    $schema: copy.$schema,
    $id: copy.$id,
    title: "LocalDataDefinitions",
    type: "object",
    additionalProperties: false,
    properties: {},
    $defs: copy.$defs,
  } as unknown as JSONSchema
  let ts = await compile(syntheticRoot, "LocalDataDefinitions", {
    bannerComment: HEADER,
    unreachableDefinitions: true,
    additionalProperties: false,
    format: true,
    declareExternallyReferenced: true,
  })
  ts = ts.replace(/export interface LocalDataDefinitions \{\}\n/, "")
  ts = ts.replace(/\n \*\n \* This interface was referenced by `LocalDataDefinitions`'s JSON-Schema\n \* via the `definition` "[^"]+"\./g, "")
  ts = ts.replace(/\/\*\*\n \* This interface was referenced by `LocalDataDefinitions`'s JSON-Schema\n \* via the `definition` "[^"]+"\.\n \*\/\n/g, "")
  if (ts.includes("LocalDataDefinitions")) fail("could not remove the synthetic root from the generated types")
  return ts
}

function generateConstants(schema: SchemaDocument): string {
  const defs = schema.$defs
  const constOf = (name: string): number => {
    const value = defs[name]?.["const"]
    if (typeof value !== "number" || !Number.isInteger(value) || value < 1) fail(`$defs.${name}.const must be a positive integer`)
    return value
  }
  const lines = [HEADER, "", 'import type * as R from "./records.ts"', ""]
  lines.push("/** Version of the record schemas = version of the IndexedDB database. */")
  lines.push(`export const SCHEMA_VERSION = ${constOf("SchemaVersion")} as const satisfies R.SchemaVersion`)
  lines.push("")
  lines.push("/** Version of the backup container format. */")
  lines.push(`export const BACKUP_FORMAT_VERSION = ${constOf("BackupFormatVersion")} as const satisfies R.BackupFormatVersion`)
  for (const [name, def] of Object.entries(ENUM_LISTS)) {
    const values = defs[def]?.["enum"]
    if (!Array.isArray(values)) fail(`$defs.${def} is not an enum`)
    lines.push("")
    lines.push(`/** Every value of ${def}. */`)
    lines.push(`export const ${name} = ${JSON.stringify(values)} as const satisfies readonly R.${def}[]`)
  }
  return `${lines.join("\n")}\n`
}

/** The schema without description/title annotations (they do not change what is valid). */
function withoutDocumentation(schema: SchemaDocument): SchemaDocument {
  const strip = (value: unknown): unknown => {
    if (Array.isArray(value)) return value.map(strip)
    if (value === null || typeof value !== "object") return value
    return Object.fromEntries(
      Object.entries(value)
        .filter(([key]) => key !== "description" && key !== "title")
        .map(([key, child]) => [key, key === "properties" || key === "$defs" ? stripMap(child) : strip(child)]),
    )
  }
  // Inside properties and $defs the keys are names, not keywords: a property may be called "title".
  const stripMap = (map: unknown): unknown =>
    Object.fromEntries(Object.entries(map as Record<string, unknown>).map(([name, child]) => [name, strip(child)]))
  return strip(schema) as SchemaDocument
}

function generateValidators(schema: SchemaDocument): string {
  const ajv = new Ajv2020({
    code: { source: true, esm: true, lines: true },
    allErrors: true,
    strict: true,
    allowUnionTypes: true,
    inlineRefs: false,
    discriminator: true,
  })
  // Annotation for json-schema-to-typescript only.
  ajv.addKeyword({ keyword: "tsType", schemaType: "string" })
  // The validators only check; the documentation stays in the schema file
  // (Ajv would otherwise copy every description into the bundle).
  ajv.addSchema(withoutDocumentation(schema))
  const refs: Record<string, string> = {}
  for (const [name, def] of Object.entries(VALIDATORS)) {
    if (!schema.$defs[def]) fail(`validator ${name}: $defs.${def} is missing`)
    refs[name] = `${schema.$id}#/$defs/${def}`
  }
  // A CommonJS module: its default export is on .default for TypeScript and Node alike.
  const code = standalone.default(ajv, refs)
  // Statements only: the schema's descriptions may well contain the word "import".
  if (/\brequire\(\s*["']|^\s*import\s[^\n]*\bfrom\s*["']/m.test(code)) {
    fail("the generated validators import Ajv runtime helpers (minLength, uniqueItems, format …); avoid those keywords so the validators stay dependency-free")
  }
  return `${HEADER}\n// @ts-nocheck\n/* eslint-disable */\n${code}\n`
}

function generateValidatorTypes(): string {
  const lines = [
    HEADER,
    "",
    'import type * as R from "./records.ts"',
    "",
    "/** One problem found by a validator (Ajv's error object, reduced to what OpenMana reads). */",
    "export interface SchemaError {",
    "  readonly instancePath: string",
    "  readonly schemaPath: string",
    "  readonly keyword: string",
    "  readonly params: Readonly<Record<string, unknown>>",
    "  readonly message?: string",
    "}",
    "",
    "/** A validator: a type guard that keeps the problems of its last call in `errors`. */",
    "export interface Validator<T> {",
    "  (data: unknown): data is T",
    "  errors?: readonly SchemaError[] | null",
    "}",
    "",
  ]
  for (const [name, def] of Object.entries(VALIDATORS)) {
    lines.push(`export declare const ${name}: Validator<R.${def}>`)
  }
  return `${lines.join("\n")}\n`
}

/** The generated files as the schema gives them: file name -> content. */
export async function generatedFiles(): Promise<Record<string, string>> {
  const schema = readSchema()
  return {
    "records.ts": await generateTypes(schema),
    "constants.ts": generateConstants(schema),
    "validators.js": generateValidators(schema),
    "validators.d.ts": generateValidatorTypes(),
  }
}

/** Generated files that differ from what is on disk (empty: up to date). */
export async function staleFiles(): Promise<string[]> {
  const outputs = await generatedFiles()
  return Object.entries(outputs)
    .filter(([file, content]) => {
      const target = path.join(outDir, file)
      return !fs.existsSync(target) || fs.readFileSync(target, "utf8") !== content
    })
    .map(([file]) => file)
}

async function main(): Promise<void> {
  if (process.argv.includes("--check")) {
    const stale = await staleFiles()
    if (stale.length > 0) {
      fail(`generated storage files are stale (${stale.join(", ")}): the schema changed without regenerating. Run \`npm run generate\` and commit the result.`)
    }
    console.error("[openmana-storage] generated files match the schema")
    return
  }
  const outputs = await generatedFiles()
  fs.mkdirSync(outDir, { recursive: true })
  for (const [file, content] of Object.entries(outputs)) {
    fs.writeFileSync(path.join(outDir, file), content)
  }
  console.error(`[openmana-storage] wrote ${Object.keys(outputs).join(", ")} to ${path.relative(root, outDir)}`)
}

if (import.meta.main) {
  try {
    await main()
  } catch (error) {
    console.error(`[openmana-storage] ERROR: ${error instanceof Error ? error.message : String(error)}`)
    process.exitCode = 1
  }
}
