#!/usr/bin/env node
// Generates the TypeScript side of the protocol from its only source,
// engine/protocol/schema/protocol.schema.json:
//
//   src/generated/protocol.ts      types (json-schema-to-typescript)
//   src/generated/constants.ts     PROTOCOL_VERSION and every enum as a runtime list
//   src/generated/validators.js    precompiled validators (Ajv standalone code:
//                                  no eval at run time, no Ajv in the bundle)
//   src/generated/validators.d.ts  their types
//
//   node protocol/scripts/generate.mjs           write the files
//   node protocol/scripts/generate.mjs --check   fail if they are not what the schema gives
//
// The generated files are committed: a schema change shows up in review as a
// diff of types and validators, and the app build needs no generator. The
// check runs in engine/scripts/build-host.sh, so a forgotten regeneration
// fails the build instead of shipping stale types.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const protocolDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaFile = path.join(protocolDir, "schema", "protocol.schema.json");
const outDir = path.join(protocolDir, "src", "generated");
const check = process.argv.includes("--check");

const HEADER = [
  "/*",
  " * GENERATED by engine/protocol/scripts/generate.mjs from",
  " * engine/protocol/schema/protocol.schema.json. Do not edit: change the schema",
  " * and run `npm run generate` in engine/.",
  " */",
].join("\n");

/** The public validators: export name -> definition in the schema. */
const VALIDATORS = {
  validateEngineMessage: "EngineMessage",
  validateEngineInput: "EngineInput",
  validateWorkerCommand: "WorkerCommand",
  validateMatchRequest: "MatchRequest",
  validateGameState: "GameState",
};

/** Enums exported as runtime lists: constant name -> definition. */
const ENUM_LISTS = {
  BOOT_PHASES: "BootPhase",
  ENGINE_ERROR_CODES: "EngineErrorCode",
  ABORT_REASONS: "AbortReason",
  PHASES: "Phase",
  MESSAGE_KINDS: "MessageKind",
  QUESTION_KINDS: "QuestionKind",
  BUTTONS_PURPOSES: "ButtonsPurpose",
  REJECT_REASONS: "RejectReason",
  GAME_RESULTS: "GameResult",
  MATCH_FORMATS: "MatchFormat",
};

function fail(message) {
  console.error(`[openmana-protocol] FEHLER: ${message}`);
  process.exit(1);
}

const schema = JSON.parse(fs.readFileSync(schemaFile, "utf8"));
const defs = schema.$defs;

/**
 * A union that is discriminated twice (Question: by type, then by kind) has
 * shared properties next to its oneOf, which the validators need for the
 * outer discriminator. json-schema-to-typescript would render that as an
 * intersection of helper types; every branch already repeats those
 * properties, so for the types the plain union of the branches is the same
 * type and reads better.
 */
function schemaForTypes() {
  const copy = structuredClone(schema);
  for (const def of Object.values(copy.$defs)) {
    if (Array.isArray(def.oneOf) && def.properties) {
      for (const branch of def.oneOf) {
        const name = branch.$ref?.replace("#/$defs/", "");
        const target = name ? copy.$defs[name] : undefined;
        if (!target?.title) fail(`nested union ${def.title}: every branch must be a $ref to a titled definition`);
        for (const key of def.required ?? []) {
          if (!target.required?.includes(key)) fail(`nested union ${def.title}: branch ${target.title} must require '${key}' itself`);
        }
      }
      delete def.type;
      delete def.required;
      delete def.properties;
      delete def.discriminator;
    }
  }
  return copy;
}

async function generateTypes() {
  // json-schema-to-typescript declares every $defs entry only below an
  // object root, so the definitions are compiled under a synthetic empty
  // object; the real root (a union of the three directions) is appended.
  const copy = schemaForTypes();
  const root = {
    $schema: copy.$schema,
    $id: copy.$id,
    title: "ProtocolDefinitions",
    type: "object",
    additionalProperties: false,
    properties: {},
    $defs: copy.$defs,
  };
  let ts = await compile(root, "ProtocolDefinitions", {
    bannerComment: HEADER,
    unreachableDefinitions: true,
    additionalProperties: false,
    format: true,
    declareExternallyReferenced: true,
  });
  // Drop the synthetic root and the tool's "referenced by" boilerplate.
  ts = ts.replace(/export interface ProtocolDefinitions \{\}\n/, "");
  ts = ts.replace(/\n \*\n \* This interface was referenced by `ProtocolDefinitions`'s JSON-Schema\n \* via the `definition` "[^"]+"\./g, "");
  ts = ts.replace(/\/\*\*\n \* This interface was referenced by `ProtocolDefinitions`'s JSON-Schema\n \* via the `definition` "[^"]+"\.\n \*\/\n/g, "");
  if (ts.includes("ProtocolDefinitions")) fail("could not remove the synthetic root from the generated types");
  const union = schema.anyOf.map((branch) => branch.$ref.replace("#/$defs/", "")).join(" | ");
  ts += `\n/**\n * ${schema.description}\n */\nexport type ${schema.title} = ${union};\n`;
  return ts;
}

function generateConstants() {
  const version = defs.ProtocolVersion?.const;
  if (!Number.isInteger(version) || version < 1) fail("$defs.ProtocolVersion.const must be a positive integer");
  const lines = [HEADER, "", 'import type * as P from "./protocol.ts";', ""];
  lines.push("/** Version of the UI<->engine contract (must equal the bridge's Protocol.VERSION). */");
  lines.push(`export const PROTOCOL_VERSION = ${version} as const satisfies P.ProtocolVersion;`);
  for (const [name, def] of Object.entries(ENUM_LISTS)) {
    const values = defs[def]?.enum;
    if (!Array.isArray(values)) fail(`$defs.${def} is not an enum`);
    lines.push("");
    lines.push(`/** Every value of ${def}. */`);
    lines.push(`export const ${name} = ${JSON.stringify(values)} as const satisfies readonly P.${def}[];`);
  }
  return lines.join("\n") + "\n";
}

function generateValidators() {
  const ajv = new Ajv2020({
    code: { source: true, esm: true, lines: true },
    allErrors: true,
    strict: true,
    allowUnionTypes: true,
    // One function per definition instead of copying e.g. the card schema into
    // every zone: about a tenth of the code, same checks.
    inlineRefs: false,
    discriminator: true,
  });
  // Annotation for json-schema-to-typescript only (the SharedArrayBuffer field).
  ajv.addKeyword({ keyword: "tsType", schemaType: "string" });
  ajv.addSchema(schema);
  const refs = {};
  for (const [name, def] of Object.entries(VALIDATORS)) {
    if (!defs[def]) fail(`validator ${name}: $defs.${def} is missing`);
    refs[name] = `${schema.$id}#/$defs/${def}`;
  }
  const code = standaloneCode(ajv, refs);
  if (/\brequire\(|\bimport\s/.test(code)) {
    fail("the generated validators import Ajv runtime helpers (minLength, uniqueItems, format ...); avoid those keywords so the validators stay dependency-free");
  }
  return `${HEADER}\n// @ts-nocheck\n/* eslint-disable */\n${code}\n`;
}

function generateValidatorTypes() {
  const lines = [
    HEADER,
    "",
    'import type * as P from "./protocol.ts";',
    "",
    "/** One problem found by a validator (Ajv's error object, reduced to what OpenMana reads). */",
    "export interface SchemaError {",
    "  readonly instancePath: string;",
    "  readonly schemaPath: string;",
    "  readonly keyword: string;",
    "  readonly params: Readonly<Record<string, unknown>>;",
    "  readonly message?: string;",
    "}",
    "",
    "/** A validator: a type guard that keeps the problems of its last call in `errors`. */",
    "export interface Validator<T> {",
    "  (data: unknown): data is T;",
    "  errors?: readonly SchemaError[] | null;",
    "}",
    "",
  ];
  for (const [name, def] of Object.entries(VALIDATORS)) {
    lines.push(`export declare const ${name}: Validator<P.${def}>;`);
  }
  return lines.join("\n") + "\n";
}

const outputs = {
  "protocol.ts": await generateTypes(),
  "constants.ts": generateConstants(),
  "validators.js": generateValidators(),
  "validators.d.ts": generateValidatorTypes(),
};

if (check) {
  const stale = Object.entries(outputs)
    .filter(([file, content]) => {
      const target = path.join(outDir, file);
      return !fs.existsSync(target) || fs.readFileSync(target, "utf8") !== content;
    })
    .map(([file]) => file);
  if (stale.length > 0) {
    fail(`generated protocol files are stale (${stale.join(", ")}). The schema changed without regenerating: run \`npm run generate\` in engine/ and commit the result.`);
  }
  console.error("[openmana-protocol] generated files match the schema");
} else {
  fs.mkdirSync(outDir, { recursive: true });
  for (const [file, content] of Object.entries(outputs)) {
    fs.writeFileSync(path.join(outDir, file), content);
  }
  console.error(`[openmana-protocol] wrote ${Object.keys(outputs).join(", ")} to ${path.relative(process.cwd(), outDir) || "."}`);
}
